### ISSUE TITLE
Loose pattern matching when writing `run.toml` 

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/haddock-runner#77]
Similar to #72, the matching is too loose and will occur in repeated entries. For example, if the pattern is for `some_fname` is `ambig` and
```go
Restraints: []string{"ambig.tbl", "ambig5.tbl", "other_unambig.tbl", "something.tbl"},
```

This will result in 

```toml
some_fname = "../data/ambig.tbl"
some_fname = "../data/ambig5.tbl"
some_fname = "../data/other_unambig.tbl"
```
